from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QLocale)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

from global_vars import *


class Ui_MainWindow(object):

# ui functions #########################################################################################################

    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1366, 768)
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1366, 768))
        MainWindow.setMaximumSize(QSize(1366, 768))
        icon = QIcon()
        icon.addFile(u"logo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.CentralWidget = QWidget(MainWindow)
        self.CentralWidget.setObjectName(u"CentralWidget")
        self.StackedWidgetMain = QStackedWidget(self.CentralWidget)
        self.StackedWidgetMain.setObjectName(u"StackedWidgetMain")
        self.StackedWidgetMain.setGeometry(QRect(0, 0, 1366, 768))
        self.StackedWidgetMain.setAcceptDrops(False)
        self.StackedWidgetMain.setFrameShape(QFrame.NoFrame)
        self.HomePage = QWidget()
        self.HomePage.setObjectName(u"HomePage")
        self.horizontalLayoutWidget = QWidget(self.HomePage)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 170, 1371, 333))
        self.LayoutHomeHorizontal = QHBoxLayout(self.horizontalLayoutWidget)
        self.LayoutHomeHorizontal.setObjectName(u"LayoutHomeHorizontal")
        self.LayoutHomeHorizontal.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutHomeHorizontal.addItem(self.horizontalSpacer_3)
        self.LayoutHomeVertical = QVBoxLayout()
        self.LayoutHomeVertical.setObjectName(u"LayoutHomeVertical")
        self.LayoutLogo = QHBoxLayout()
        self.LayoutLogo.setObjectName(u"LayoutLogo")
        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutLogo.addItem(self.horizontalSpacer_7)
        self.LabelLogo = QLabel(self.horizontalLayoutWidget)
        self.LabelLogo.setObjectName(u"LabelLogo")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.LabelLogo.sizePolicy().hasHeightForWidth())
        self.LabelLogo.setSizePolicy(sizePolicy1)
        self.LabelLogo.setMaximumSize(QSize(200, 200))
        self.LabelLogo.setPixmap(QPixmap(u"logo.png"))
        self.LabelLogo.setScaledContents(True)
        self.LayoutLogo.addWidget(self.LabelLogo)
        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutLogo.addItem(self.horizontalSpacer_8)
        self.LayoutHomeVertical.addLayout(self.LayoutLogo)
        self.LabelWelcome = QLabel(self.horizontalLayoutWidget)
        self.LabelWelcome.setObjectName(u"LabelWelcome")
        font = QFont()
        font.setFamily(u"Cambria")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.LabelWelcome.setFont(font)
        self.LabelWelcome.setLayoutDirection(Qt.LeftToRight)
        self.LabelWelcome.setFrameShape(QFrame.NoFrame)
        self.LabelWelcome.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.LayoutHomeVertical.addWidget(self.LabelWelcome)
        self.LayoutInput = QHBoxLayout()
        self.LayoutInput.setObjectName(u"LayoutInput")
        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutInput.addItem(self.horizontalSpacer_9)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(self.verticalSpacer_2)
        self.LineOrg = QLineEdit(self.horizontalLayoutWidget)
        self.LineOrg.setObjectName(u"LineOrg")
        sizePolicy1.setHeightForWidth(self.LineOrg.sizePolicy().hasHeightForWidth())
        self.LineOrg.setSizePolicy(sizePolicy1)
        self.LineOrg.setMinimumSize(QSize(200, 25))
        self.verticalLayout.addWidget(self.LineOrg)
        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(self.verticalSpacer)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer_16 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(self.horizontalSpacer_16)
        self.ButtonGo = QPushButton(self.horizontalLayoutWidget)
        self.ButtonGo.setObjectName(u"ButtonGo")
        self.ButtonGo.setEnabled(True)
        self.ButtonGo.setCheckable(False)
        self.horizontalLayout.addWidget(self.ButtonGo)
        self.horizontalSpacer_18 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(self.horizontalSpacer_18)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.LayoutInput.addLayout(self.verticalLayout)
        self.horizontalSpacer_10 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutInput.addItem(self.horizontalSpacer_10)
        self.LayoutHomeVertical.addLayout(self.LayoutInput)
        self.LayoutHomeHorizontal.addLayout(self.LayoutHomeVertical)
        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutHomeHorizontal.addItem(self.horizontalSpacer_4)
        self.StackedWidgetMain.addWidget(self.HomePage)
        self.ErrorPage = QWidget()
        self.ErrorPage.setObjectName(u"ErrorPage")
        self.LabelError = QLabel(self.ErrorPage)
        self.LabelError.setObjectName(u"LabelError")
        self.LabelError.setGeometry(QRect(450, 330, 481, 91))
        font1 = QFont()
        font1.setPointSize(20)
        self.LabelError.setFont(font1)
        self.ButtonGoBack = QPushButton(self.ErrorPage)
        self.ButtonGoBack.setObjectName(u"ButtonGoBack")
        self.ButtonGoBack.setGeometry(QRect(630, 410, 75, 23))
        self.ButtonGoBack.setCheckable(False)
        self.StackedWidgetMain.addWidget(self.ErrorPage)
        self.UserPage = QWidget()
        self.UserPage.setObjectName(u"UserPage")
        self.StackedWidgetUserTypes = QStackedWidget(self.UserPage)
        self.StackedWidgetUserTypes.setObjectName(u"StackedWidgetUserTypes")
        self.StackedWidgetUserTypes.setGeometry(QRect(150, 20, 231, 111))
        self.GuestPage = QWidget()
        self.GuestPage.setObjectName(u"GuestPage")
        self.verticalLayoutWidget_2 = QWidget(self.GuestPage)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 20, 201, 91))
        self.LayoutLogIn = QVBoxLayout(self.verticalLayoutWidget_2)
        self.LayoutLogIn.setObjectName(u"LayoutLogIn")
        self.LayoutLogIn.setSizeConstraint(QLayout.SetFixedSize)
        self.LayoutLogIn.setContentsMargins(0, 0, 0, 0)
        self.LineUser = QLineEdit(self.verticalLayoutWidget_2)
        self.LineUser.setObjectName(u"LineUser")
        self.LineUser.setInputMethodHints(Qt.ImhHiddenText)
        self.LayoutLogIn.addWidget(self.LineUser)
        self.LinePass = QLineEdit(self.verticalLayoutWidget_2)
        self.LinePass.setObjectName(u"LinePass")
        self.LinePass.setEchoMode(QLineEdit.Password)
        self.LayoutLogIn.addWidget(self.LinePass)
        self.LayoutButton = QHBoxLayout()
        self.LayoutButton.setObjectName(u"LayoutButton")
        self.horizontalSpacer_11 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutButton.addItem(self.horizontalSpacer_11)
        self.ButtonLogIn = QPushButton(self.verticalLayoutWidget_2)
        self.ButtonLogIn.setObjectName(u"ButtonLogIn")
        self.ButtonLogIn.setCheckable(False)
        self.LayoutButton.addWidget(self.ButtonLogIn)
        self.horizontalSpacer_12 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutButton.addItem(self.horizontalSpacer_12)
        self.LayoutLogIn.addLayout(self.LayoutButton)
        self.StackedWidgetUserTypes.addWidget(self.GuestPage)
        self.LoggedUserPage = QWidget()
        self.LoggedUserPage.setObjectName(u"LoggedUserPage")
        self.verticalLayoutWidget = QWidget(self.LoggedUserPage)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 210, 54))
        self.LayoutLoggedIn = QVBoxLayout(self.verticalLayoutWidget)
        self.LayoutLoggedIn.setObjectName(u"LayoutLoggedIn")
        self.LayoutLoggedIn.setContentsMargins(0, 0, 0, 0)
        self.LayoutWelcomeUser = QHBoxLayout()
        self.LayoutWelcomeUser.setObjectName(u"LayoutWelcomeUser")
        self.LabelWelcomeUser = QLabel(self.verticalLayoutWidget)
        self.LabelWelcomeUser.setObjectName(u"LabelWelcomeUser")
        font2 = QFont()
        font2.setPointSize(12)
        self.LabelWelcomeUser.setFont(font2)
        self.LayoutWelcomeUser.addWidget(self.LabelWelcomeUser)
        self.LabelLoggedUser = QLabel(self.verticalLayoutWidget)
        self.LabelLoggedUser.setObjectName(u"LabelLoggedUser")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.LabelLoggedUser.sizePolicy().hasHeightForWidth())
        self.LabelLoggedUser.setSizePolicy(sizePolicy2)
        self.LabelLoggedUser.setFont(font2)
        self.LabelLoggedUser.setStyleSheet(u"color : rgb(5, 76, 181)")
        self.LayoutWelcomeUser.addWidget(self.LabelLoggedUser)
        self.LayoutLoggedIn.addLayout(self.LayoutWelcomeUser)
        self.LayoutLogOut = QHBoxLayout()
        self.LayoutLogOut.setObjectName(u"LayoutLogOut")
        self.ButtonLogOut = QPushButton(self.verticalLayoutWidget)
        self.ButtonLogOut.setObjectName(u"ButtonLogOut")
        self.ButtonLogOut.setMinimumSize(QSize(90, 0))
        self.ButtonLogOut.setMaximumSize(QSize(90, 16777215))
        self.ButtonLogOut.setCheckable(False)
        self.LayoutLogOut.addWidget(self.ButtonLogOut)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutLogOut.addItem(self.horizontalSpacer_2)
        self.LayoutLoggedIn.addLayout(self.LayoutLogOut)
        self.ButtonMessages = QToolButton(self.LoggedUserPage)
        self.ButtonMessages.setObjectName(u"ButtonMessages")
        self.ButtonMessages.setGeometry(QRect(0, 60, 41, 41))
        icon1 = QIcon()
        icon1.addFile(u"message.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ButtonMessages.setIcon(icon1)
        self.ButtonMessages.setIconSize(QSize(30, 30))
        self.ButtonMessages.setCheckable(False)
        self.ButtonEdit = QToolButton(self.LoggedUserPage)
        self.ButtonEdit.setObjectName(u"ButtonEdit")
        self.ButtonEdit.setGeometry(QRect(50, 60, 41, 41))
        icon2 = QIcon()
        icon2.addFile(u"edit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ButtonEdit.setIcon(icon2)
        self.ButtonEdit.setIconSize(QSize(30, 30))
        self.ButtonEdit.setCheckable(False)
        self.StackedWidgetUserTypes.addWidget(self.LoggedUserPage)
        self.LabelLogo_2 = QLabel(self.UserPage)
        self.LabelLogo_2.setObjectName(u"LabelLogo_2")
        self.LabelLogo_2.setGeometry(QRect(30, 20, 111, 111))
        sizePolicy1.setHeightForWidth(self.LabelLogo_2.sizePolicy().hasHeightForWidth())
        self.LabelLogo_2.setSizePolicy(sizePolicy1)
        self.LabelLogo_2.setMaximumSize(QSize(200, 200))
        self.LabelLogo_2.setPixmap(QPixmap(u"logo.png"))
        self.LabelLogo_2.setScaledContents(True)
        self.formLayoutWidget = QWidget(self.UserPage)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(40, 134, 1281, 611))
        self.LayoutMainView = QGridLayout(self.formLayoutWidget)
        self.LayoutMainView.setObjectName(u"LayoutMainView")
        self.LayoutMainView.setContentsMargins(0, 0, 0, 0)
        self.LayoutSelectView = QHBoxLayout()
        self.LayoutSelectView.setObjectName(u"LayoutSelectView")
        self.LayoutSelectView.setSizeConstraint(QLayout.SetFixedSize)
        self.horizontalSpacer_13 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutSelectView.addItem(self.horizontalSpacer_13)
        self.LayoutButtons = QHBoxLayout()
        self.LayoutButtons.setObjectName(u"LayoutButtons")
        self.LayoutButtons.setSizeConstraint(QLayout.SetFixedSize)
        self.ButtonGrid = QPushButton(self.formLayoutWidget)
        self.ButtonGrid.setObjectName(u"ButtonGrid")
        self.ButtonGrid.setCheckable(True)
        self.ButtonGrid.setChecked(False)
        self.ButtonGrid.setAutoExclusive(True)
        self.LayoutButtons.addWidget(self.ButtonGrid)
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.LayoutButtons.addItem(self.horizontalSpacer)
        self.ButtonCalendar = QPushButton(self.formLayoutWidget)
        self.ButtonCalendar.setObjectName(u"ButtonCalendar")
        self.ButtonCalendar.setCheckable(True)
        self.ButtonCalendar.setAutoExclusive(True)
        self.LayoutButtons.addWidget(self.ButtonCalendar)
        self.LayoutSelectView.addLayout(self.LayoutButtons)
        self.horizontalSpacer_14 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutSelectView.addItem(self.horizontalSpacer_14)
        self.LayoutMainView.addLayout(self.LayoutSelectView, 3, 0, 1, 1)
        self.MainView = QStackedWidget(self.formLayoutWidget)
        self.MainView.setObjectName(u"MainView")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.MainView.sizePolicy().hasHeightForWidth())
        self.MainView.setSizePolicy(sizePolicy3)
        self.MainView.setMinimumSize(QSize(500, 500))
        self.MainView.setMaximumSize(QSize(2000, 500))
        self.MainView.setFrameShape(QFrame.NoFrame)
        self.GridView = QWidget()
        self.GridView.setObjectName(u"GridView")
        self.horizontalLayoutWidget_5 = QWidget(self.GridView)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(0, 456, 1281, 41))
        self.LayoutGridToolbar = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.LayoutGridToolbar.setObjectName(u"LayoutGridToolbar")
        self.LayoutGridToolbar.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_19 = QSpacerItem(20, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.LayoutGridToolbar.addItem(self.horizontalSpacer_19)
        self.LabelFloor = QLabel(self.horizontalLayoutWidget_5)
        self.LabelFloor.setObjectName(u"LabelFloor")
        self.LabelFloor.setMinimumSize(QSize(0, 25))
        self.LabelFloor.setMaximumSize(QSize(16777215, 25))
        self.LabelFloor.setAlignment(Qt.AlignCenter)
        self.LayoutGridToolbar.addWidget(self.LabelFloor)
        self.SpinBoxFloor = QSpinBox(self.horizontalLayoutWidget_5)
        self.SpinBoxFloor.setObjectName(u"SpinBoxFloor")
        self.LayoutGridToolbar.addWidget(self.SpinBoxFloor)
        self.horizontalSpacer_15 = QSpacerItem(243, 18, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutGridToolbar.addItem(self.horizontalSpacer_15)
        self.ButtonGridRevert = QPushButton(self.horizontalLayoutWidget_5)
        self.ButtonGridRevert.setObjectName(u"ButtonGridRevert")
        self.ButtonGridRevert.setCheckable(False)
        self.ButtonGridRevert.setAutoRepeat(False)
        self.LayoutGridToolbar.addWidget(self.ButtonGridRevert)
        self.ButtonGridPublish = QPushButton(self.horizontalLayoutWidget_5)
        self.ButtonGridPublish.setObjectName(u"ButtonGridPublish")
        self.ButtonGridPublish.setCheckable(False)
        self.LayoutGridToolbar.addWidget(self.ButtonGridPublish)
        self.FrameGrid = QFrame(self.GridView)
        self.FrameGrid.setObjectName(u"FrameGrid")
        self.FrameGrid.setGeometry(QRect(0, 0, 1281, 451))
        self.FrameGrid.setFrameShape(QFrame.Box)
        self.FrameGrid.setFrameShadow(QFrame.Raised)
        self.gridLayoutWidget = QWidget(self.FrameGrid)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 0, 1281, 451))
        self.Grid = QGridLayout(self.gridLayoutWidget)
        self.Grid.setSpacing(0)
        self.Grid.setObjectName(u"Grid")
        self.Grid.setContentsMargins(0, 0, 0, 0)
        self.pushButton = QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy1.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy1)
        self.pushButton.setMinimumSize(QSize(100, 100))
        self.pushButton.setMaximumSize(QSize(100, 100))
        self.Grid.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy1.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy1)
        self.pushButton_3.setMinimumSize(QSize(100, 100))
        self.pushButton_3.setMaximumSize(QSize(100, 100))
        self.Grid.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_2 = QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        sizePolicy1.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy1)
        self.pushButton_2.setMinimumSize(QSize(100, 100))
        self.pushButton_2.setMaximumSize(QSize(100, 100))
        self.Grid.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_4 = QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        sizePolicy1.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy1)
        self.pushButton_4.setMinimumSize(QSize(100, 100))
        self.pushButton_4.setMaximumSize(QSize(100, 100))
        self.Grid.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        sizePolicy1.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy1)
        self.pushButton_5.setMinimumSize(QSize(100, 100))
        self.pushButton_5.setMaximumSize(QSize(100, 100))
        self.Grid.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.MainView.addWidget(self.GridView)
        self.CalendarView = QWidget()
        self.CalendarView.setObjectName(u"CalendarView")
        self.horizontalLayoutWidget_6 = QWidget(self.CalendarView)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(0, 456, 1281, 41))
        self.LayoutCalToolbar = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.LayoutCalToolbar.setObjectName(u"LayoutCalToolbar")
        self.LayoutCalToolbar.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_17 = QSpacerItem(243, 18, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutCalToolbar.addItem(self.horizontalSpacer_17)
        self.ButtonCalPublish = QPushButton(self.horizontalLayoutWidget_6)
        self.ButtonCalPublish.setObjectName(u"ButtonCalPublish")
        self.ButtonCalPublish.setCheckable(False)
        self.ButtonCalPublish.setChecked(False)
        self.ButtonCalPublish.setAutoRepeat(False)
        self.LayoutCalToolbar.addWidget(self.ButtonCalPublish)
        self.ButtonCalRevert = QPushButton(self.horizontalLayoutWidget_6)
        self.ButtonCalRevert.setObjectName(u"ButtonCalRevert")
        self.ButtonCalRevert.setCheckable(False)
        self.LayoutCalToolbar.addWidget(self.ButtonCalRevert)
        self.ButtonDownload = QToolButton(self.horizontalLayoutWidget_6)
        self.ButtonDownload.setObjectName(u"ButtonDownload")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(41)
        sizePolicy4.setVerticalStretch(41)
        sizePolicy4.setHeightForWidth(self.ButtonDownload.sizePolicy().hasHeightForWidth())
        self.ButtonDownload.setSizePolicy(sizePolicy4)
        icon3 = QIcon()
        icon3.addFile(u"save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ButtonDownload.setIcon(icon3)
        self.ButtonDownload.setIconSize(QSize(30, 30))
        self.ButtonDownload.setCheckable(True)
        self.LayoutCalToolbar.addWidget(self.ButtonDownload)
        self.FrameCalendar = QFrame(self.CalendarView)
        self.FrameCalendar.setObjectName(u"FrameCalendar")
        self.FrameCalendar.setGeometry(QRect(0, 0, 1281, 451))
        self.FrameCalendar.setFrameShape(QFrame.Box)
        self.FrameCalendar.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget_7 = QWidget(self.FrameCalendar)
        self.horizontalLayoutWidget_7.setObjectName(u"horizontalLayoutWidget_7")
        self.horizontalLayoutWidget_7.setGeometry(QRect(10, 10, 1261, 431))
        self.LayoutCalendar = QHBoxLayout(self.horizontalLayoutWidget_7)
        self.LayoutCalendar.setObjectName(u"LayoutCalendar")
        self.LayoutCalendar.setContentsMargins(0, 0, 0, 0)
        self.Calendar = QCalendarWidget(self.horizontalLayoutWidget_7)
        self.Calendar.setObjectName(u"Calendar")
        self.Calendar.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.Calendar.setMaximumDate(QDate(9999, 12, 30))
        self.Calendar.setGridVisible(False)
        self.LayoutCalendar.addWidget(self.Calendar)
        self.ListWidgetEvents = QListWidget(self.horizontalLayoutWidget_7)
        QListWidgetItem(self.ListWidgetEvents)
        QListWidgetItem(self.ListWidgetEvents)
        self.ListWidgetEvents.setObjectName(u"ListWidgetEvents")
        sizePolicy5 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.ListWidgetEvents.sizePolicy().hasHeightForWidth())
        self.ListWidgetEvents.setSizePolicy(sizePolicy5)
        self.ListWidgetEvents.setMinimumSize(QSize(300, 0))
        self.ListWidgetEvents.setMaximumSize(QSize(300, 16777215))
        font3 = QFont()
        font3.setKerning(True)
        self.ListWidgetEvents.setFont(font3)
        self.ListWidgetEvents.setFrameShape(QFrame.NoFrame)
        self.ListWidgetEvents.setAlternatingRowColors(True)
        self.LayoutCalendar.addWidget(self.ListWidgetEvents)
        self.MainView.addWidget(self.CalendarView)
        self.LayoutMainView.addWidget(self.MainView, 2, 0, 1, 1)
        self.LayoutToolbar = QHBoxLayout()
        self.LayoutToolbar.setObjectName(u"LayoutToolbar")
        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.LayoutToolbar.addItem(self.horizontalSpacer_5)
        self.LayoutComboBoxVertical = QVBoxLayout()
        self.LayoutComboBoxVertical.setObjectName(u"LayoutComboBoxVertical")
        self.ComboBoxBuildings = QComboBox(self.formLayoutWidget)
        self.ComboBoxBuildings.addItem("")
        self.ComboBoxBuildings.addItem("")
        self.ComboBoxBuildings.addItem("")
        self.ComboBoxBuildings.addItem("")
        self.ComboBoxBuildings.setObjectName(u"ComboBoxBuildings")
        font4 = QFont()
        font4.setPointSize(11)
        font4.setItalic(False)
        font4.setStrikeOut(False)
        self.ComboBoxBuildings.setFont(font4)
        self.ComboBoxBuildings.setFrame(True)
        self.LayoutComboBoxVertical.addWidget(self.ComboBoxBuildings)
        self.ComboBoxFilters = QComboBox(self.formLayoutWidget)
        self.ComboBoxFilters.addItem("")
        self.ComboBoxFilters.addItem("")
        self.ComboBoxFilters.addItem("")
        self.ComboBoxFilters.addItem("")
        self.ComboBoxFilters.setObjectName(u"ComboBoxFilters")
        self.ComboBoxFilters.setFrame(True)
        self.LayoutComboBoxVertical.addWidget(self.ComboBoxFilters)
        self.LayoutToolbar.addLayout(self.LayoutComboBoxVertical)
        self.horizontalSpacer_6 = QSpacerItem(500, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.LayoutToolbar.addItem(self.horizontalSpacer_6)
        self.ButtonSearch = QToolButton(self.formLayoutWidget)
        self.ButtonSearch.setObjectName(u"ButtonSearch")
        icon4 = QIcon()
        icon4.addFile(u"search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ButtonSearch.setIcon(icon4)
        self.ButtonSearch.setIconSize(QSize(30, 30))
        self.ButtonSearch.setCheckable(False)
        self.LayoutToolbar.addWidget(self.ButtonSearch)
        self.LayoutMainView.addLayout(self.LayoutToolbar, 1, 0, 1, 1)
        self.StackedWidgetMain.addWidget(self.UserPage)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.retranslateUi(MainWindow)

        self.StackedWidgetMain.setCurrentIndex(0)
        self.StackedWidgetUserTypes.setCurrentIndex(0)
        self.MainView.setCurrentIndex(0)
        self.ButtonGridPublish.hide()
        self.ButtonGridRevert.hide()
        self.ButtonCalPublish.hide()
        self.ButtonCalRevert.hide()

        QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MasterPlan", None))
        self.LabelLogo.setText("")
        self.LabelWelcome.setText(QCoreApplication.translate("MainWindow", u"MasterPlan", None))
        self.LineOrg.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter organization", None))
        self.ButtonGo.setText(QCoreApplication.translate("MainWindow", u"Go", None))
        self.LabelError.setText(QCoreApplication.translate("MainWindow", u"Sorry, there is no such organization. :(", None))
        self.ButtonGoBack.setText(QCoreApplication.translate("MainWindow", u"Go back", None))
        self.LineUser.setPlaceholderText(QCoreApplication.translate("MainWindow", u"username", None))
        self.LinePass.setPlaceholderText(QCoreApplication.translate("MainWindow", u"password", None))
        self.ButtonLogIn.setText(QCoreApplication.translate("MainWindow", u"Log in", None))
        self.LabelWelcomeUser.setText(QCoreApplication.translate("MainWindow", u"Welcome,", None))
        self.LabelLoggedUser.setText(QCoreApplication.translate("MainWindow", u"<user name>", None))
        self.ButtonLogOut.setText(QCoreApplication.translate("MainWindow", u"Log out", None))
        self.ButtonMessages.setText(QCoreApplication.translate("MainWindow", u"Messages", None))
        self.ButtonEdit.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.LabelLogo_2.setText("")
        self.ButtonGrid.setText(QCoreApplication.translate("MainWindow", u"Grid View", None))
        self.ButtonCalendar.setText(QCoreApplication.translate("MainWindow", u"Calendar View", None))
        self.LabelFloor.setText(QCoreApplication.translate("MainWindow", u"Floor", None))
        self.ButtonGridRevert.setText(QCoreApplication.translate("MainWindow", u"Revert Changes", None))
        self.ButtonGridPublish.setText(QCoreApplication.translate("MainWindow", u"Publish Changes", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Room1", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Room3", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Room2", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Room4", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Room5", None))
        self.ButtonCalPublish.setText(QCoreApplication.translate("MainWindow", u"Publish Changes", None))
        self.ButtonCalRevert.setText(QCoreApplication.translate("MainWindow", u"Revert Changes", None))
        self.ButtonDownload.setText(QCoreApplication.translate("MainWindow", u"...", None))

        __sortingEnabled = self.ListWidgetEvents.isSortingEnabled()
        self.ListWidgetEvents.setSortingEnabled(False)
        ___qlistwidgetitem = self.ListWidgetEvents.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"Event 1 today", None));
        ___qlistwidgetitem1 = self.ListWidgetEvents.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Event 2 today", None));
        self.ListWidgetEvents.setSortingEnabled(__sortingEnabled)

        self.ComboBoxBuildings.setItemText(0, QCoreApplication.translate("MainWindow", u"No Building Selected", None))
        self.ComboBoxBuildings.setItemText(1, QCoreApplication.translate("MainWindow", u"Building 1", None))
        self.ComboBoxBuildings.setItemText(2, QCoreApplication.translate("MainWindow", u"Building 2", None))
        self.ComboBoxBuildings.setItemText(3, QCoreApplication.translate("MainWindow", u"Building 3", None))

        self.ComboBoxFilters.setItemText(0, QCoreApplication.translate("MainWindow", u"No Filter Selected", None))
        self.ComboBoxFilters.setItemText(1, QCoreApplication.translate("MainWindow", u"Filter 1", None))
        self.ComboBoxFilters.setItemText(2, QCoreApplication.translate("MainWindow", u"Filter 2", None))
        self.ComboBoxFilters.setItemText(3, QCoreApplication.translate("MainWindow", u"Filter 3", None))

        self.ButtonSearch.setText(QCoreApplication.translate("MainWindow", u"Search", None))



    def connectSignals(self):
        self.ButtonGo.clicked.connect(self.enterOrganization)
        self.ButtonGoBack.clicked.connect(self.showHomePage)
        self.ButtonLogIn.clicked.connect(self.logIn)
        self.ButtonLogOut.clicked.connect(self.logOut)
        self.ButtonEdit.clicked.connect(self.selectEventList)
        self.ButtonSearch.clicked.connect(self.selectSearch)
        self.ButtonGrid.clicked.connect(self.showGrid)
        self.ButtonCalendar.clicked.connect(self.showCalendar)
        self.ButtonDownload.clicked.connect(self.download)


    # domain functions #################################################################################################

    def showHomePage(self):
        self.StackedWidgetMain.setCurrentIndex(0)

    def showErrorPage(self):
        self.StackedWidgetMain.setCurrentIndex(1)

    def showUserPage(self):
        self.StackedWidgetMain.setCurrentIndex(2)

    def showGuestPage(self):
        self.StackedWidgetUserTypes.setCurrentIndex(0)

    def showLoggedUserPage(self):
        self.StackedWidgetUserTypes.setCurrentIndex(1)

    def enterOrganization(self):
        org = self.LineOrg.text()
        if account_list.valOrganization(org):
            self.showUserPage()
            self.showGuestPage()
        else:
            self.showErrorPage()

    def logIn(self):
        username = self.LineUser.text()
        password = self.LinePass.text()
        account = account_list.accountExists(username, password)
        if account:
            self.showLoggedUserPage()
            self.LabelLoggedUser.setText(account.username)
            session = Session(account)
            print(session)
        else:
            print("Account not found") #show MessageWindow

    def logOut(self):
        session = None
        self.LineUser.setText(None)
        self.LinePass.setText(None)
        self.showGuestPage()

    def selectEventList(self):
        print("Open Event List Window") #show EventListWindow

    def selectSearch(self):
        print("Open Search Window") #show SearchWindow

    def showGrid(self):
        self.MainView.setCurrentIndex(0)

    def showCalendar(self):
        self.MainView.setCurrentIndex(1)

    def download(self):
        print("download calendar")
