

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(225, 362)
        self.AddTagConst_page = QStackedWidget(Dialog)
        self.AddTagConst_page.setObjectName(u"AddTagConst_page")
        self.AddTagConst_page.setGeometry(QRect(10, 60, 181, 191))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.AddTagConst_page.setFont(font)
        self.AddTimeConst_page_2 = QWidget()
        self.AddTimeConst_page_2.setObjectName(u"AddTimeConst_page_2")
        self.dateTimeEdit = QDateTimeEdit(self.AddTimeConst_page_2)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(30, 30, 121, 22))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit_2 = QDateTimeEdit(self.AddTimeConst_page_2)
        self.dateTimeEdit_2.setObjectName(u"dateTimeEdit_2")
        self.dateTimeEdit_2.setGeometry(QRect(30, 90, 121, 22))
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.label_3 = QLabel(self.AddTimeConst_page_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 10, 61, 16))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.AddTimeConst_page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 70, 47, 13))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.AddTimeConst_page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 130, 71, 16))
        self.label_5.setFont(font1)
        self.comboBox = QComboBox(self.AddTimeConst_page_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(30, 150, 69, 22))
        self.AddTagConst_page.addWidget(self.AddTimeConst_page_2)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 50, 61, 20))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(250, 70, 71, 21))
        self.label_8.setFont(font1)
        self.horizontalSlider_2 = QSlider(self.page_2)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(250, 100, 121, 21))
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.comboBox_2 = QComboBox(self.page_2)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(20, 70, 69, 22))
        self.horizontalSlider_3 = QSlider(self.page_2)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setGeometry(QRect(30, 200, 131, 21))
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.AddTagConst_page.addWidget(self.page_2)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 151, 21))
        font2 = QFont()
        font2.setPointSize(13)
        font2.setBold(True)
        font2.setWeight(75)
        self.label.setFont(font2)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 41, 21))
        self.Add_btn = QPushButton(Dialog)
        self.Add_btn.setObjectName(u"Add_btn")
        self.Add_btn.setGeometry(QRect(30, 330, 61, 21))
        self.horizontalSlider = QSlider(Dialog)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(30, 270, 131, 21))
        self.horizontalSlider.setMaximum(2)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksBothSides)
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 250, 71, 16))
        self.label_6.setFont(font1)
        self.EventValue = QLabel(Dialog)
        self.EventValue.setObjectName(u"EventValue")
        self.EventValue.setGeometry(QRect(50, 40, 71, 20))

        self.retranslateUi(Dialog)

        self.AddTagConst_page.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Starts at:", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Ends at:", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Repetition:", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"None", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"Daily", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"Weekly", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"Monthly", None))

        self.label_7.setText(QCoreApplication.translate("Dialog", u"Add Tag:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Set Weight:", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Add Constraint", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Event: ", None))
        self.Add_btn.setText(QCoreApplication.translate("Dialog", u"Add", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Set weight:", None))
        self.EventValue.setText(QCoreApplication.translate("Dialog", u"Event Name", None))
    # retranslateUi

